# Generated by Django 2.2 on 2019-05-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
