# Generated by Django 2.2 on 2019-05-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20190509_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservación 🤯', 'verbose_name_plural': 'reservaciones'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name',)},
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123pass456', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
